custom_prompt: "pick the tube from the right rack and insert into the left rack"
data_dir:
  - "/data/das/vio_260108_3eps"
action_ori_type: "quaternion"
action_prediction_step: 1
contain_ft: false
contain_depth: false
repo_name: "260108_3eps_ee2ee"
root_path: "/data/fr3_lerobot"
fps: 30
num_writer_thread: 4
num_writer_process: 0
batch_encoding_size: 1
video_backend: torchcodec
rotation_transform:
  single: [0.7071068, 0, 0.7071068, 0]
